# Created by newuser for 5.0.5
#

# broken links
eval $(dircolors -b)

autoload -U compinit promptinit
compinit
promptinit

autoload -U colors && colors

# For autocompletion with an arrow-key driven interface
zstyle ':completion:*' menu select

HISTFILE=~/.zsh/.histfile-$UID
HISTSIZE=1000
SAVEHIST=1000

source ~/.zsh/git-prompt.sh

for rcfile ($HOME/.zsh/rc/*.zsh) source $rcfile

############# Display stuff after login #############
have fortune && echo -e "\e[1;33m$(fortune -c)\e[00m"
echo
date

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/home/stan/data/coding/cpp/cocos2d-x-3.3/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=/home/stan/data/coding/cpp/cocos2d-x-3.3
export PATH=$COCOS_X_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/home/stan/data/coding/cpp/cocos2d-x-3.3/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

# Add environment variable NDK_ROOT for cocos2d-x
export NDK_ROOT=/home/stan/data/coding/android-ndk-r10d
export PATH=$NDK_ROOT:$PATH

# Add environment variable ANDROID_SDK_ROOT for cocos2d-x
export ANDROID_SDK_ROOT=/home/stan/data/coding/android-sdk-linux
export PATH=$ANDROID_SDK_ROOT:$PATH
export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

# Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/home/stan/data/coding/apache-ant-1.9.4/bin/
export PATH=$ANT_ROOT:$PATH
